spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: test
          uri: lb://TEST
          predicates:
            - Path=/api/v1/test/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**

eureka:
#  client:
#    service-url:
#      defaultZone: http://192.168.1.3:8761/eureka
  instance:
    prefer-ip-address: true
