server:
  port: 9000

spring:
  application:
    name:
      command
  kafka:
    consumer:
      group-id: command
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: localhost:9092
eureka:
  client:
    service-url:
      defaultUrl: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true # ???

